#!/usr/bin/env bash

while getopts ":har" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    local_db -h        Display this help message"
      echo "    local_db -a        Start docker postgres database"
      echo "    local_db -r        Stop and remove docker postgres database"
      exit 0
      ;;
    a )
      docker pull postgres:11
      docker run --name ESQLA-postgres --env POSTGRES_PASSWORD=postgres --detach --publish 5432:5432 postgres:11
      ;;
    r )
      docker stop ESQLA-postgres
      docker rm ESQLA-postgres
      ;;
  esac
done
